import Head from 'next/head';
import { getXataClient } from '../src/xata';

const xata = getXataClient();
const Home = ({ todos }) => {
  console.log(xata);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Xata todos app</h1>

      <div>
        <form>
          {todos.map((t) => (
            <label htmlFor='todos' key={t.id}>
              <input checked={t.is_done} type='checkbox' />
              {t.label}
            </label>
          ))}
        </form>
      </div>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const todos = await xata.db.items.getAll();
  return {
    props: {
      todos,
    },
  };
}
